### ISSUE TITLE
Document how to contribute

### ISSUE THREAD

**Issue by gianpaj** [flaki/checkinfox#15]
I'd like to help but would be nice if you could write a short guide on how to get started, and short guide to the source code.

**Comment by flaki** [comment]
Hey gianpaj! I'm very happy that you are interested in contributing! Please stay put, as I'm currently refactoring Check-in Fox to ease working with the code. After the refactoring it will be much easier to pick up the development. So stay tuned, will notify you as soon as the refactoring work is done!

**Comment by gianpaj** [comment]
:+1:
